import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  DEFAULT_OUTPUT_DIR,
  doctorProject,
  readJson,
  writeJson,
} from './core.mjs';

export const RESIDENT_STATUS_FILE = 'resident-status.json';
export const CONTEXT_PACK_FILE = 'context-pack.json';
export const CODEX_MCP_TOML_FILE = 'codex-mcp.toml';
export const CODEX_MCP_INSTALL_FILE = 'CODEX_MCP_INSTALL.md';

function portablePath(filePath) {
  return filePath.replace(/\\/g, '/');
}

function relativePortable(from, to) {
  const relative = path.relative(from, to) || '.';
  return portablePath(relative);
}

function resolveWorkspace({ targetDir = process.cwd(), outputDir = null } = {}) {
  const root = path.resolve(targetDir);
  const resolvedOutput = path.resolve(outputDir || path.join(root, DEFAULT_OUTPUT_DIR));
  return { root, outputDir: resolvedOutput };
}

function readJsonIfPresent(filePath) {
  if (!fs.existsSync(filePath)) return null;
  try {
    return readJson(filePath);
  } catch (error) {
    return {
      parse_error: error.message,
    };
  }
}

function artifactStatus(root, outputDir, fileName) {
  const filePath = path.join(outputDir, fileName);
  const exists = fs.existsSync(filePath);
  let parsed = null;
  if (exists) parsed = readJsonIfPresent(filePath);
  return {
    name: fileName,
    exists,
    path: relativePortable(root, filePath),
    schema: parsed?.schema || parsed?.schema_version || null,
    parse_error: parsed?.parse_error || null,
  };
}

function standardArtifacts(root, outputDir) {
  return [
    artifactStatus(root, outputDir, 'policy.json'),
    artifactStatus(root, outputDir, 'source-map.json'),
    artifactStatus(root, outputDir, 'context-packet.json'),
    artifactStatus(root, outputDir, 'policy-summary.json'),
    artifactStatus(root, outputDir, 'deployment-preview.json'),
    artifactStatus(root, outputDir, 'harness-export.json'),
  ];
}

function authorityBoundary() {
  return {
    local_only: true,
    no_cloud_call: true,
    no_deploy: true,
    no_spend: true,
    no_wallet_mutation: true,
    no_x402_settlement: true,
    no_marketplace_publication: true,
    no_provider_ranking: true,
    full_ecf_private_internals_included: false,
    raw_secret_content_included: false,
  };
}

function tomlString(value) {
  return JSON.stringify(String(value));
}

function workspaceHash(root) {
  return crypto.createHash('sha1').update(path.resolve(root)).digest('hex').slice(0, 8);
}

function codexServerName(root, requestedName = null) {
  if (requestedName) return requestedName.replace(/[^A-Za-z0-9_]/g, '_');
  return `micro_ecf_resident_${workspaceHash(root)}`;
}

function packageCliPath() {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'micro-ecf.mjs');
}

function codexConfigPath(codexHome = null) {
  const home = codexHome
    || process.env.CODEX_HOME
    || path.join(process.env.USERPROFILE || process.env.HOME || '', '.codex');
  return path.join(home, 'config.toml');
}

function buildCodexMcpToml({ root, outputDir, serverName = null } = {}) {
  const name = codexServerName(root, serverName);
  const cliPath = packageCliPath();
  return {
    server_name: name,
    cli_path: cliPath,
    artifact_root: outputDir,
    toml: [
      `# Micro ECF resident MCP server for ${portablePath(root)}`,
      `# Generated by: micro-ecf mcp-config --target codex`,
      `[mcp_servers.${name}]`,
      `command = ${tomlString(process.execPath)}`,
      `args = [ ${tomlString(cliPath)}, "serve-mcp", "--root", ${tomlString(outputDir)} ]`,
      '',
    ].join('\n'),
  };
}

function buildCodexInstallDoc({ root, outputDir, serverName, snippetPath, configPath }) {
  return `# Micro ECF Codex MCP Install

This workspace can expose Micro ECF as a local Codex MCP server.

## Generated server

- Server: \`${serverName}\`
- Workspace: \`${portablePath(root)}\`
- Artifact root: \`${portablePath(outputDir)}\`
- Snippet: \`${portablePath(snippetPath)}\`
- Codex config target: \`${portablePath(configPath)}\`

## Install

\`\`\`bash
micro-ecf mcp-config --target codex --dir . --write --install-codex
\`\`\`

Restart Codex after installation. MCP servers are loaded when Codex starts.

## Boundary

This MCP server is local-only. It reads Micro ECF artifacts and does not deploy, spend, mutate wallets, settle x402, publish marketplace listings, rank providers, or expose Full ECF private internals.
`;
}

function replaceMarkedBlock(existing, blockName, block) {
  const begin = `# BEGIN ${blockName}`;
  const end = `# END ${blockName}`;
  const wrapped = `${begin}\n${block.trimEnd()}\n${end}\n`;
  const pattern = new RegExp(`${begin.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${end.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\n?`, 'm');
  if (pattern.test(existing)) return existing.replace(pattern, wrapped);
  const separator = existing.trim().length ? '\n\n' : '';
  return `${existing.trimEnd()}${separator}${wrapped}`;
}

function installCodexMcpConfig({ configPath, serverName, toml }) {
  const blockName = `Micro ECF resident ${serverName}`;
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  const existing = fs.existsSync(configPath) ? fs.readFileSync(configPath, 'utf8') : '';
  const updated = replaceMarkedBlock(existing, blockName, toml);
  fs.writeFileSync(configPath, updated);
  return configPath;
}

function sourceCounts(sourceMap) {
  const sources = Array.isArray(sourceMap?.sources) ? sourceMap.sources : [];
  const blocked = Array.isArray(sourceMap?.blocked) ? sourceMap.blocked : [];
  return {
    included_sources: sourceMap?.stats?.included_sources ?? sources.length,
    blocked_paths: sourceMap?.stats?.blocked_paths ?? blocked.length,
    allowed_roots: sourceMap?.policy?.allowed_roots || [],
  };
}

function policySummary(policySummaryArtifact) {
  if (!policySummaryArtifact || policySummaryArtifact.parse_error) return null;
  return {
    agent: policySummaryArtifact.agent?.name || policySummaryArtifact.agent_name || null,
    primary_goal: policySummaryArtifact.agent?.primary_goal || policySummaryArtifact.primary_goal || null,
    allowed_tools: policySummaryArtifact.allowed_tools || [],
    blocked_tools: policySummaryArtifact.blocked_tools || [],
    public_api_enabled: policySummaryArtifact.api_policy?.public_api_enabled === true,
    marketplace_can_buy: policySummaryArtifact.marketplace_policy?.can_buy === true,
    marketplace_can_sell: policySummaryArtifact.marketplace_policy?.can_sell === true,
  };
}

export function buildMicroEcfResidentStatus(options = {}) {
  const { root, outputDir } = resolveWorkspace(options);
  const doctor = doctorProject({ targetDir: root, outputDir });
  const artifacts = standardArtifacts(root, outputDir);
  const missing = artifacts.filter((artifact) => !artifact.exists).map((artifact) => artifact.name);
  const ready = doctor.ok === true;

  return {
    schema: 'agoragentic.micro-ecf.resident-status.v1',
    ok: ready,
    resident_state: ready ? 'ready' : 'attention_required',
    generated_at: new Date().toISOString(),
    workspace_root: relativePortable(process.cwd(), root),
    output_dir: relativePortable(process.cwd(), outputDir),
    checks: doctor.checks,
    missing_artifacts: missing,
    artifacts,
    codex_context: {
      repo_instructions_present: fs.existsSync(path.join(root, 'AGENTS.md')),
      ecf_md_present: fs.existsSync(path.join(root, 'ECF.md')),
      llm_bootstrap_present: fs.existsSync(path.join(root, 'MICRO_ECF_LLM_BOOTSTRAP.md')),
      disclosure_required: true,
    },
    mcp: {
      available: true,
      command: `micro-ecf serve-mcp --root ${relativePortable(root, outputDir)}`,
      tools: [
        'micro_ecf.search_context',
        'micro_ecf.get_source',
        'micro_ecf.get_policy',
        'micro_ecf.build_packet',
        'micro_ecf.context_pack',
        'micro_ecf.status',
        'micro_ecf.worklog_status',
        'micro_ecf.handoff',
        'micro_ecf.work_memory',
      ],
    },
    context_pack: {
      available: missing.includes('context-packet.json') === false
        && missing.includes('policy-summary.json') === false
        && missing.includes('source-map.json') === false,
      command: `micro-ecf context-pack --dir ${relativePortable(process.cwd(), root)} --write`,
    },
    authority_boundary: authorityBoundary(),
    next_steps: doctor.next_steps,
  };
}

export function writeMicroEcfResidentStatus(options = {}) {
  const { outputDir } = resolveWorkspace(options);
  const status = buildMicroEcfResidentStatus(options);
  const outputPath = writeJson(path.join(outputDir, RESIDENT_STATUS_FILE), status);
  return {
    ...status,
    status_path: relativePortable(process.cwd(), outputPath),
  };
}

export function buildMicroEcfContextPack(options = {}) {
  const { root, outputDir } = resolveWorkspace(options);
  const task = String(options.task || '').trim() || 'current_codex_session';
  const status = buildMicroEcfResidentStatus({ targetDir: root, outputDir });
  const sourceMap = readJsonIfPresent(path.join(outputDir, 'source-map.json'));
  const contextPacket = readJsonIfPresent(path.join(outputDir, 'context-packet.json'));
  const policySummaryArtifact = readJsonIfPresent(path.join(outputDir, 'policy-summary.json'));
  const deploymentPreview = readJsonIfPresent(path.join(outputDir, 'deployment-preview.json'));

  return {
    schema: 'agoragentic.micro-ecf.context-pack.v1',
    ok: status.ok,
    task,
    generated_at: new Date().toISOString(),
    workspace_root: relativePortable(process.cwd(), root),
    output_dir: relativePortable(process.cwd(), outputDir),
    status_ref: relativePortable(root, path.join(outputDir, RESIDENT_STATUS_FILE)),
    artifacts: {
      source_map: relativePortable(root, path.join(outputDir, 'source-map.json')),
      context_packet: relativePortable(root, path.join(outputDir, 'context-packet.json')),
      policy_summary: relativePortable(root, path.join(outputDir, 'policy-summary.json')),
      deployment_preview: relativePortable(root, path.join(outputDir, 'deployment-preview.json')),
      harness_export: relativePortable(root, path.join(outputDir, 'harness-export.json')),
    },
    summary: {
      source_counts: sourceCounts(sourceMap),
      citation_count: Array.isArray(contextPacket?.citations) ? contextPacket.citations.length : 0,
      policy: policySummary(policySummaryArtifact),
      deployment_preview_state: deploymentPreview?.readiness?.status || deploymentPreview?.status || null,
      missing_artifacts: status.missing_artifacts,
    },
    assistant_bootstrap: {
      read_order: [
        'AGENTS.md',
        'ECF.md',
        'MICRO_ECF_LLM_BOOTSTRAP.md',
        '.micro-ecf/context-packet.json',
        '.micro-ecf/policy-summary.json',
        '.micro-ecf/worklog/latest-summary.md',
        '.micro-ecf/next-session.md',
      ],
      disclosure: 'Micro ECF resident context is local-only and must be refreshed from local artifacts; it is not hidden global memory.',
      refresh_commands: [
        'micro-ecf doctor --dir .',
        'micro-ecf build-packet --output-dir .micro-ecf',
        'micro-ecf status --dir . --write',
        'micro-ecf context-pack --dir . --write',
        'micro-ecf docs-sync plan --dir .',
        'micro-ecf handoff --write',
      ],
    },
    authority_boundary: authorityBoundary(),
  };
}

export function writeMicroEcfContextPack(options = {}) {
  const { outputDir } = resolveWorkspace(options);
  const pack = buildMicroEcfContextPack(options);
  const outputPath = writeJson(path.join(outputDir, CONTEXT_PACK_FILE), pack);
  return {
    ...pack,
    context_pack_path: relativePortable(process.cwd(), outputPath),
  };
}

export function buildMicroEcfMcpConfig(options = {}) {
  const target = options.target || 'codex';
  if (target !== 'codex') throw new Error('Only --target codex is supported for Micro ECF MCP config.');
  const { root, outputDir } = resolveWorkspace(options);
  const configPath = codexConfigPath(options.codexHome);
  const { server_name: serverName, cli_path: cliPath, artifact_root: artifactRoot, toml } = buildCodexMcpToml({
    root,
    outputDir,
    serverName: options.serverName,
  });
  return {
    schema: 'agoragentic.micro-ecf.mcp-config.v1',
    ok: true,
    target,
    generated_at: new Date().toISOString(),
    workspace_root: relativePortable(process.cwd(), root),
    output_dir: relativePortable(process.cwd(), outputDir),
    server_name: serverName,
    command: process.execPath,
    args: [cliPath, 'serve-mcp', '--root', artifactRoot],
    codex_config_path: configPath,
    restart_required: true,
    toml,
    authority_boundary: authorityBoundary(),
  };
}

export function writeMicroEcfMcpConfig(options = {}) {
  const { root, outputDir } = resolveWorkspace(options);
  const config = buildMicroEcfMcpConfig(options);
  const snippetPath = writeJson(path.join(outputDir, CODEX_MCP_TOML_FILE.replace(/\.toml$/, '.json')), {
    schema: 'agoragentic.micro-ecf.mcp-config-artifact.v1',
    server_name: config.server_name,
    codex_config_path: config.codex_config_path,
    restart_required: config.restart_required,
    toml: config.toml,
    authority_boundary: config.authority_boundary,
  });
  const tomlPath = path.join(outputDir, CODEX_MCP_TOML_FILE);
  fs.mkdirSync(path.dirname(tomlPath), { recursive: true });
  fs.writeFileSync(tomlPath, config.toml);
  const installDocPath = path.join(outputDir, CODEX_MCP_INSTALL_FILE);
  fs.writeFileSync(installDocPath, buildCodexInstallDoc({
    root,
    outputDir,
    serverName: config.server_name,
    snippetPath: tomlPath,
    configPath: config.codex_config_path,
  }));
  let installedPath = null;
  if (options.installCodex) {
    installedPath = installCodexMcpConfig({
      configPath: config.codex_config_path,
      serverName: config.server_name,
      toml: config.toml,
    });
  }
  return {
    ...config,
    written: true,
    snippet_path: relativePortable(process.cwd(), tomlPath),
    snippet_json_path: relativePortable(process.cwd(), snippetPath),
    install_doc_path: relativePortable(process.cwd(), installDocPath),
    codex_config_updated: Boolean(installedPath),
    codex_config_path: installedPath || config.codex_config_path,
  };
}
